# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unweave < Formula
  desc "Supabase for Machine Learning"
  homepage "https://unweave.io"
  version "0.1.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unweave/cli/releases/download/v0.1.25/unweave_0.1.25_Darwin_x86_64.tar.gz"
      sha256 "642bcceab1c7b68c4f9d1e956df3e88d1fddabdfecce06b27c8c6ab0c23e1610"

      def install
        bin.install "unweave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unweave/cli/releases/download/v0.1.25/unweave_0.1.25_Darwin_arm64.tar.gz"
      sha256 "dc2038f19979d959d1c37c21d1a968368e953634c90e6a74ec077aa0720b76eb"

      def install
        bin.install "unweave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/unweave/cli/releases/download/v0.1.25/unweave_0.1.25_Linux_x86_64.tar.gz"
      sha256 "21448c43c21c70426b99076ec8db50e3401a7552da033ac5026a29ec9071ae4e"

      def install
        bin.install "unweave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unweave/cli/releases/download/v0.1.25/unweave_0.1.25_Linux_arm64.tar.gz"
      sha256 "644bd3105a967172da953898bed5bed3da621e669c1c4b92ed8ecded21694391"

      def install
        bin.install "unweave"
      end
    end
  end

  test do
    system "#{bin}/unweave"
  end
end
